### ISSUE TITLE
[问题]: SkinsRestorer软依赖加载错误

### ISSUE THREAD

**Issue by Ummio** [CoderKuo/TrMenu#100] opened 2024-08-31 12:07 UTC
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2024-08-31 19:52:19)

| Server OS: Linux amd64 6.8.0-39-generic
| Server software: git-Leaf-"13ff24f" (MC: 1.20.4) (1.20.4-R0.1-SNAPSHOT)
| Java version: 21.0.3

| TrMenu: 3.3.3a
Installed Plugins: 
· BetonQuest - 2.1.3 (0 KB)
· BreweryX - 3.2.3-SNAPSHOT (0 KB)
· CMI - 9.7.5.3 (0 KB)
· CMIEInjector - 1.0.2.4 (0 KB)
· CMILib - 1.5.1.1 (0 KB)
· Citizens - 2.0.33-SNAPSHOT (build 3389) (0 KB)
· CoinsEngine - 2.3.4 (0 KB)
· CommandWhitelist - 2.10.0 (0 KB)
· ConsoleSpamFix - 1.10.0 (0 KB)
· CoreProtect - 22.4 (0 KB)
· CustomCrops - 3.5.10 (0 KB)
· CustomFishing - 2.2.21 (0 KB)
· CustomNameplates - 2.4.5 (0 KB)
· Denizen - 1.3.0-SNAPSHOT (build 1804-REL) (0 KB)
· EliteMobs - 8.7.16 (0 KB)
· FastAsyncWorldEdit - 2.11.2-SNAPSHOT-879;d1e2511 (0 KB)
· HMCColor - 2.1 (0 KB)
· HMCCosmetics - 2.7.3 (0 KB)
· HibiscusCommons - 0.4.6 (0 KB)
· HuskHomes - 4.7 (0 KB)
· HuskHomesGUI - 2.3 (0 KB)
· HuskSync - 3.5 (0 KB)
· Images - 2.5.1 (0 KB)
· ItemsAdder - 3.6.4 (0 KB)
· Lands - 7.1.11 (0 KB)
· LibsDisguises - 10.0.44-SNAPSHOT (0 KB)
· LoneLibs - 1.0.54 (0 KB)
· LuckPerms - 5.4.139 (0 KB)
· PlaceholderAPI - 2.11.6 (0 KB)
· PlugManX - 2.4.0 (0 KB)
· ProtocolLib - 5.2.0-SNAPSHOT-679 (0 KB)
· SkinsRestorer - 15.4.2 (0 KB)
· Skript - 2.9.1 (0 KB)
· TrChat - 2.1.0 (0 KB)
· TrMenu - 3.3.3a (0 KB)
· TradeMe - 6.2.1.4 (0 KB)
· UseTranslatedNames - 2.3.1 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· XConomy - 2.26.3 (0 KB)
· mcMMO - 2.2.014 (0 KB)
· nightcore - 2.6.3 (0 KB)
· packetevents - 2.5.0+f4bb1dd8f-SNAPSHOT (0 KB)
· spark - 1.10.99 (0 KB)

### 🔍 详细的描述

已使用最新版TrMenu及SkinsRestore
在服务端开启时已明确出现
[TrMenu] HOOK | Soft-Dependency SkinsRestorer is hooked.
当使用图标'head:%player_name%'则出现提示
[TrMenu] HOOK | Attempted to use the non-installed soft-depend plugin SkinsRestorer

### 🗄 服务端日志

```
[19:49:03 INFO]: [SkinsRestorer] Enabling SkinsRestorer v15.4.2
[19:49:04 WARN]: [SkinsRestorer] You must agree to the rules at 'commands.perSkinPermissionsConsent' in the config to use per skin permissions.
[19:49:04 INFO]: [SkinsRestorer] -------------------------/Warning\-------------------------
[19:49:04 INFO]: [SkinsRestorer] This plugin is running in PROXY mode!
[19:49:04 INFO]: [SkinsRestorer] You have to do all configuration at config file
[19:49:04 INFO]: [SkinsRestorer] inside your BungeeCord/Velocity server.
[19:49:04 INFO]: [SkinsRestorer] (<proxy>/plugins/SkinsRestorer/)
[19:49:04 INFO]: [SkinsRestorer] -------------------------\Warning/-------------------------
[19:49:04 INFO]: [SkinsRestorer] Running on Minecraft 1.20.4.
[19:49:04 INFO]: [PlaceholderAPI] Successfully registered internal expansion: skinsrestorer [15.4.2]
[19:49:04 INFO]: [SkinsRestorer] PlaceholderAPI expansion registered!
[19:49:04 INFO]: [SkinsRestorer] ----------------------------------------------
[19:49:04 INFO]: [SkinsRestorer]     +==================+
[19:49:04 INFO]: [SkinsRestorer]     |   SkinsRestorer  |
[19:49:04 INFO]: [SkinsRestorer]     |------------------|
[19:49:04 INFO]: [SkinsRestorer]     |    Proxy Mode    |
[19:49:04 INFO]: [SkinsRestorer]     +==================+
[19:49:04 INFO]: [SkinsRestorer] ----------------------------------------------
[19:49:04 INFO]: [SkinsRestorer]     Version: 15.4.2
[19:49:04 INFO]: [SkinsRestorer]     Commit: 210a436
[19:49:04 INFO]: [SkinsRestorer]     This is the latest version!
[19:49:04 INFO]: [SkinsRestorer] ----------------------------------------------

[19:49:20 INFO]: [TrMenu] FINE | 17 menus were loaded (776 ms)
[19:49:20 INFO]: [TrMenu] INFO | Plugin has been enabled. Currently running version 3.3.3a.
[19:49:20 INFO]: {Plugin-Version}
[19:49:20 INFO]: [TrMenu] HOOK | Soft-Dependency Vault is hooked.
[19:49:20 INFO]: [TrMenu] HOOK | Soft-Dependency HMCCosmetics is hooked.
[19:49:20 INFO]: [TrMenu] HOOK | Soft-Dependency SkinsRestorer is hooked.
[19:49:20 INFO]: [TrMenu] HOOK | Soft-Dependency ItemsAdder is hooked.

[19:49:42 INFO]: [TrMenu] HOOK | Attempted to use the non-installed soft-depend plugin SkinsRestorer
```

### ⚙ 配置文件

```

```

**Comment by humonia-sys** [comment] 2024-09-22 12:25
So I got the same problem, and I found the problem is that skinsrestorer is actually not working in proxy mode, so refer to "(README) Use proxy config for settings! (README).txt", if you need to use skinsrestorer api, you have to create a blank file named "enableSkinStorageAPI.txt" in skinsrestorer's data dir.

Don't forget to configure your MySQL settings!


> SkinsRestorer is running in "Proxy Mode"
> 
> If you are NOT using a proxy (BungeeCord, Waterfall or Velocity) in your network, set spigot.yml -> bungeecord: false
> 
> Using a proxy? --> You MUST use proxy installation! (or use override files)
> 
> What is "Proxy Mode"?
> The proxy will handle SkinsRestorer's commands, API, permission, database and config in a "centralized" manner.
> 
> How to install on proxy?
> Please read: https://skinsrestorer.net/docs/installation#platform-installation
> 
> Your proxy will now tell all your backend servers what to do!
> You may now configure SkinsRestorer on your proxy (<proxy>/plugins/SkinsRestorer)
> 
> --- Override Files ---
> 
> **Backend API:**
> **You can enable the backend storage by creating a file called enableSkinStorageAPI.txt in SkinsRestorer folder (backend server -> ./plugins/SkinsRestorer/enableSkinStorageAPI.txt)**
> **This is useful when using plugins like BedWars, Dynmap, etc. that need to get the skin through API from the backend server.**
> Keep in mind that connecting **MySQL** to the same database as the proxy is required for this to work!
> 
> ProxyMode:
> Warning: Disabling ProxyMode will force the backend to handle everything including applying skin on join. This is not recommended as the proxy has way better control over the player connection.
> How to turn off proxy mode: create a file called disableProxyMode.txt in SkinsRestorer folder (backend server -> ./plugins/SkinsRestorer/disableProxyMode.txt)
> This will force disable proxy mode on next restart.
>

**Comment by humonia-sys** [comment] 2024-09-22 12:26
And I think it's not TrMenu's fault, should close this issue.

**Comment by Ummio** [comment] 2024-09-22 12:49
> And I think it's not TrMenu's fault, should close this issue.而且我认为这不是 TrMenu 的错，应该解决这个问题。

ok，I will free time try

**Closed as completed** 2024-11-09 13:03 UTC
